apiVersion: v1
kind: Namespace
metadata:
  name: magic-flow
  labels:
    name: magic-flow
    app: magic-flow
    version: v2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: magic-flow-config
  namespace: magic-flow
  labels:
    app: magic-flow
data:
  config.yaml: |
    environment: production
    
    server:
      host: "0.0.0.0"
      port: 8080
      read_timeout: 30s
      write_timeout: 30s
      idle_timeout: 60s
      tls:
        enabled: true
        cert_file: "/etc/ssl/certs/tls.crt"
        key_file: "/etc/ssl/private/tls.key"
    
    database:
      host: "postgres-service"
      port: 5432
      name: "magic_flow"
      user: "magic_flow"
      password: "${DATABASE_PASSWORD}"
      ssl_mode: "require"
      max_open_conns: 25
      max_idle_conns: 5
      conn_max_lifetime: 300s
    
    redis:
      host: "redis-service"
      port: 6379
      password: "${REDIS_PASSWORD}"
      db: 0
      pool_size: 10
    
    engine:
      max_concurrent_workflows: 100
      step_timeout: 300s
      cleanup_interval: 3600s
      retry_attempts: 3
      retry_delay: 5s
    
    dashboard:
      enabled: true
      port: 8081
      websocket_enabled: true
      metrics_interval: 30s
    
    code_generation:
      enabled: true
      output_dir: "/app/generated"
      templates_dir: "/app/templates"
      languages: ["go", "typescript", "python", "java"]
    
    versioning:
      enabled: true
      retention_days: 90
      max_versions: 50
      auto_cleanup: true
    
    security:
      authentication:
        enabled: true
        jwt:
          secret: "${JWT_SECRET}"
          expiry: 24h
          refresh_expiry: 168h
      rate_limit:
        enabled: true
        requests_per_minute: 100
        burst: 200
      cors:
        enabled: true
        allowed_origins: ["https://magic-flow.example.com"]
        allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
        allowed_headers: ["*"]
    
    logging:
      level: "info"
      format: "json"
      output: "stdout"
    
    metrics:
      enabled: true
      port: 9090
      path: "/metrics"
      namespace: "magic_flow"
    
    features:
      dashboard: true
      code_generation: true
      versioning: true
      metrics: true
      authentication: true
      rate_limiting: true